### PR TITLE
allow custom invoice type for fetch

### PR DESCRIPTION
**Pull request by Kukks**
Ran into a scenario where I needed to serialize info to json but the ShouldSerialize properties made it ignore some key elements such as `Status`.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I don't like those `Should` methods, can I just replace it with `, DefaultValueHandling = DefaultValueHandling.Ignore` on the fields?

**Comment by NicolasDorier** [comment]
Use `InvoiceResponse` in BTCpay

**Comment by Kukks** [comment]
Issue is not in Btcpay, using it in the external fiat system. As long as there is a way to override this behavior I am good. 
Here is how I managed with this PR:
```csharp
var invoices = await client.GetInvoicesAsync<BtcPayInvoice>(data.PairedDate);

public class BtcPayInvoice : Invoice
    {
        public override bool ShouldSerializeId()
        {
            return true;
        }

        public override bool ShouldSerializeUrl()
        {
            return true;
        }

        public override bool ShouldSerializeStatus()
        {
            return true;
        }

        public override bool ShouldSerializeBtcPrice()
        {
            return true;
        }

        public override bool ShouldSerializeInvoiceTime()
        {
            return true;
        }

        public override bool ShouldSerializeExpirationTime()
        {
            return true;
        }

        public override bool ShouldSerializeBtcPaid()
        {
            return true;
        }

        public override bool ShouldSerializeBtcDue()
        {
            return true;
        }

        public override bool ShouldSerializeTransactions()
        {
            return true;
        }

        public override bool ShouldSerializeExRates()
        {
            return true;
        }

        public override bool ShouldSerializeExceptionStatus()
        {
            return true;
        }

        public override bool ShouldSerializePaymentUrls()
        {
            return true;
        }

        public override bool ShouldSerializeAddresses()
        {
            return true;
        }
    }
```

**Comment by NicolasDorier** [comment]
Should we just replace the Invoice type here with the InvoiceResponse one from BTCPay (without renaming the Invoice type here though)

**Comment by Kukks** [comment]
I looked into it & `Invoice Response` misses some properties (such as fullnotifications, buyerXXX fields, etc)

**Comment by NicolasDorier** [comment]
In BTCPay today I just created https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Models/CreateInvoiceRequest.cs

The problem is that this lib is using the same type for both, the request and the response.

**Comment by Kukks** [comment]
So we should move both formats to this lib and do a breaking change? It should be fairly minor and good in the long run

**Comment by NicolasDorier** [comment]
I think this convention driven stuff is ugly. But well, will merge.

**Comment by Kukks** [comment]
I agree, but it's what's in there right now :)

**Pull request merged**
