### PR TITLE
send rates signed to support btcpayserver's slightly different rates api requirement

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Actually the rate should not need to be signed.

**Comment by Kukks** [comment]
No they don't but to connect to the new btcpayserver ones we need a way to
get the store id and I think if you sign it, we can resolve it from that.

I don't think think there is any harm of signing it anyway right?

On Jul 28, 2018 13:55, "Nicolas Dorier" <notifications@github.com> wrote:

Actually the rate should not need to be signed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MetacoSA/NBitpayClient/pull/15#issuecomment-408602179>,
or mute the thread

**Comment by NicolasDorier** [comment]
Oh I see that's indeed cool.

**Comment by NicolasDorier** [comment]
It still works fine on bitpay?

**Pull request merged**
